name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy to www
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      
    - name: Install dependencies
      run: bundle install
      
    - name: Run build
      run: bundle exec jekyll b --config _config-prod.yml
      
    - name: Deploy via rsync
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "--verbose --recursive --times --compress --delete-after"
        SOURCE: "_site/*"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
